/**
 * Regenerates `infra/agent-egress/opencode-providers.tsv` from models.dev — the
 * catalog OpenCode itself is built from.
 *
 * The TSV is the ONE place the factory learns which OpenCode providers exist,
 * what they are called, and which API base they talk to. Three consumers read
 * it so nothing about a provider is ever typed twice:
 *   - infra/agent-egress/render.sh   → Squid ACL + CoreDNS zones for the
 *                                      providers enabled by OPENCODE_PROVIDERS;
 *   - src/runner/providerBroker.ts    → upstream URL the credential broker
 *                                      forwards to on behalf of the sandbox;
 *   - the accounts UI (via executor)  → provider names in the connect form.
 *
 * Providers whose SDK package bakes the base URL in (Anthropic, OpenAI, …) have
 * no `api` field on models.dev; their well-known defaults live in SDK_DEFAULTS
 * below. Providers with a templated URL (`${ACCOUNT_ID}`), a non-http URL or no
 * resolvable base are left out: the factory cannot route them, so it must not
 * pretend to.
 *
 *   pnpm tsx scripts/refresh-opencode-catalog.ts   # then commit the TSV
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

const SOURCE = 'https://models.dev/api.json';
const TARGET = path.resolve('infra/agent-egress/opencode-providers.tsv');

/** Base URLs the @ai-sdk/* packages use when models.dev leaves `api` empty. */
const SDK_DEFAULTS: Record<string, string> = {
  anthropic: 'https://api.anthropic.com/v1',
  openai: 'https://api.openai.com/v1',
  google: 'https://generativelanguage.googleapis.com/v1beta',
  mistral: 'https://api.mistral.ai/v1',
  groq: 'https://api.groq.com/openai/v1',
  xai: 'https://api.x.ai/v1',
  cerebras: 'https://api.cerebras.ai/v1',
  cohere: 'https://api.cohere.com/v2',
  deepinfra: 'https://api.deepinfra.com/v1/openai',
  togetherai: 'https://api.together.xyz/v1',
  perplexity: 'https://api.perplexity.ai',
};

interface CatalogProvider { name?: string; api?: string }

function usableBase(id: string, entry: CatalogProvider): string | null {
  const candidate = (entry.api ?? SDK_DEFAULTS[id] ?? '').trim();
  if (!candidate || candidate.includes('${')) return null;
  let url: URL;
  try { url = new URL(candidate); } catch { return null; }
  if (url.protocol !== 'https:') return null;
  if (/^(localhost|127\.|\[::1\])/.test(url.hostname)) return null;
  return url.toString().replace(/\/+$/, '');
}

async function main(): Promise<void> {
  const response = await fetch(SOURCE, { signal: AbortSignal.timeout(30_000) });
  if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}`);
  const catalog = await response.json() as Record<string, CatalogProvider>;

  const rows: string[] = [];
  let skipped = 0;
  for (const id of Object.keys(catalog).sort()) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) { skipped++; continue; }
    const base = usableBase(id, catalog[id]!);
    if (!base) { skipped++; continue; }
    const name = (catalog[id]!.name ?? id).replace(/[\t\n]/g, ' ').trim();
    rows.push(`${id}\t${name}\t${base}`);
  }

  const header = [
    '# OpenCode provider catalog — generated by scripts/refresh-opencode-catalog.ts',
    `# from ${SOURCE} on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`,
    '# id<TAB>display name<TAB>API base URL (https only, no templates)',
  ];
  await writeFile(TARGET, `${[...header, ...rows].join('\n')}\n`, 'utf8');
  console.log(`wrote ${rows.length} providers to ${path.relative(process.cwd(), TARGET)} (${skipped} unroutable skipped)`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
